# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ltilaunch', '0003_auto_20160914_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('body', models.TextField(default='')),
                ('on_run', models.TextField(default='def on_run(code, output, properties):\n    return True')),
                ('on_step', models.TextField(default='def on_step(code, output, properties):\n    return True')),
                ('on_start', models.TextField(default='')),
                ('answer', models.TextField(default='')),
                ('due', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.CharField(default='normal', max_length=10)),
                ('visibility', models.CharField(default='visible', max_length=10)),
                ('disabled', models.CharField(default='enabled', max_length=10)),
                ('mode', models.CharField(default='blocks', max_length=10)),
                ('version', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Untitled', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Assignment')),
                ('assignment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.AssignmentGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('service', models.CharField(default='', max_length=80)),
                ('external_id', models.CharField(default='', max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(default='', max_length=255)),
                ('action', models.CharField(default='', max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(max_length=80)),
                ('connected', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('assignment_version', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Course'),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_django_skeleton.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIUser'),
        ),
    ]
