# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltilaunch', '0001_squashed_0002_auto_20160804_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitoolprovider',
            name='visibility',
            field=models.CharField(blank=True, choices=[('', 'All'), ('admins', 'Admins'), ('members', 'Members')], max_length=10),
        ),
    ]
