# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltilaunch', '0002_auto_20160828_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiuser',
            name='lti_tool_consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltilaunch.LTIToolConsumer', verbose_name='LTI tool consumer'),
        ),
        migrations.AlterField(
            model_name='ltiuser',
            name='lti_user_id',
            field=models.TextField(verbose_name='LTI user ID'),
        ),
    ]
